export enum GenreEnum {
  ANIMATED = 'animated',
  BIOGRAPHY = 'biography',
  ACTION = 'action',
  WESTERN = 'western',
  WAR = 'war',
  DETECTIVE = 'detective',
  CHILDREN_AND_FAMILY = 'children/family',
  DOCUMENTARY = 'documentary',
  DRAMA = 'drama',
  HISTORICAL = 'historical',
  COMEDY = 'comedy',
  CRIME = 'crime',
  ROMANCE = 'romance',
  MUSIC = 'music',
  MUSICAL = 'musical',
  ADVENTURE = 'adventure',
  THRILLER = 'thriller',
  HORROR = 'horror',
  FANTASY = 'fantasy',
}